// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCke6wvdDb8JATjHOjHv6iNNUbMo_VHCto',
    appId: '1:578164487582:web:546cf0060b4eb45d72528f',
    messagingSenderId: '578164487582',
    projectId: 'unipocket-ab50e',
    authDomain: 'unipocket-ab50e.firebaseapp.com',
    storageBucket: 'unipocket-ab50e.firebasestorage.app',
    measurementId: 'G-4FJFPLCPHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXzenvY6LNUePwaQ_D6AJwh213TSCKIQ',
    appId: '1:578164487582:android:dc5b2457036688f472528f',
    messagingSenderId: '578164487582',
    projectId: 'unipocket-ab50e',
    storageBucket: 'unipocket-ab50e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCke6wvdDb8JATjHOjHv6iNNUbMo_VHCto',
    appId: '1:578164487582:web:4bec6c3f937edeea72528f',
    messagingSenderId: '578164487582',
    projectId: 'unipocket-ab50e',
    authDomain: 'unipocket-ab50e.firebaseapp.com',
    storageBucket: 'unipocket-ab50e.firebasestorage.app',
    measurementId: 'G-N3ZPNJLEYF',
  );
}
